#!/usr/bin/env perl

use strict;

my $hubdir = '/var/aw';

my $uname = `uname`;

create_system_user("aw-hub");
create_system_user("aw-logger");

if (-d $hubdir) {
  print "Hub directory '$hubdir' already exists, skipping creation...\n";
} elsif (-e $hubdir) {
  print "Hub directory '$hubdir' exists and is not a directory, skipping creation...\n";
} else {
  print "Creating hub directory '$hubdir'\n";
  mkdir($hubdir) || die "unable to mkdir $hubdir : $!";

  open(FH, "> $hubdir/hub.conf");
  print FH <<END;
(hub-uid "aw-hub")
(logger-uid "aw-logger")
(max-fds 10000)
(listen "0.0.0.0" 80)

;; For custom dispatching logic (see FAQ):
;; (inherit "/path/to/hub-inc.conf")
END
  close(FH);

  mkdir("$hubdir/empty") || die "unable to mkdir $hubdir/empty : $!";

  mkdir("$hubdir/aw_log") || die "unable to mkdir $hubdir/aw_log : $!";
  system("chown aw-logger $hubdir/aw_log");
  system("chgrp aw-logger $hubdir/aw_log");
}


print <<'END';

Congratulations, Antiweb is installed!

What's next?

1) Create a worker user:

  sudo adduser --quiet --system --group --no-create-home my-website

2) Create a worker conf file and edit it:

  antiweb -skel-worker-basic > /web/etc/my-website.conf
  vi /web/etc/my-website.conf

3) Start the processes:

  sudo antiweb -hub /var/aw
  sudo antiweb -worker /etc/web/my-website.conf

END

exit 0;



## UTILS

sub create_system_user {
  my $user = shift;

  `id $user 2>&1`;

  if ($?) {
    print "Creating user '$user'...\n";

    if ($uname =~ /linux/i) {
      my $ret = system("adduser --quiet --system --group --no-create-home $user");
      die "Unable to add user '$user'" if $ret;
    } else {
      die "unsupported platform";
    }
  } else {
    print "User '$user' already exists, skipping creation...\n";
  }
}
