;; Antiweb (C) Doug Hoyte

(defun lookup-mime-type (m types)
  (cadar (member m types :key #'car :test #'equalp)))

(defvar aw-default-mime-type
  "text/plain; charset=utf-8")

(defvar aw-mime-types '(
  ("html" "text/html; charset=utf-8")
  ("htm" "text/html; charset=utf-8")
  ("txt" "text/plain; charset=utf-8")
  ("css" "text/css")
  ("js" "application/x-javascript")
  ("png" "image/png")
  ("gif" "image/gif")
  ("jpg" "image/jpeg")
  ("jpeg" "image/jpeg")
  ("ico" "image/vnd.microsoft.icon")
  ("wml" "text/vnd.wap.wml")
  ("tif" "image/tiff")
  ("tar" "application/x-tar")
  ("tgz" "application/x-gzip")
  ("gz" "application/x-gzip")
  ("bz2" "application/x-bzip2")
  ("rar" "application/x-rar-compressed")
  ("zip" "application/x-zip-compressed")
  ("pdf" "application/pdf")
  ("deb" "application/x-debian-package")
  ("xml" "text/xml")
  ("dtd" "text/xml")
  ("wav" "audio/wav")
  ("mid" "audio/midi")
  ("midi" "audio/midi")
  ("mp3" "audio/mpeg")
  ("mpg" "video/mpeg")
  ("mpeg" "video/mpeg")
  ("swf" "application/x-shockwave-flash")
  ("qt" "video/quicktime")
  ("mov" "video/quicktime")
  ("avi" "video/x-msvideo")
  ("a" "application/octet-stream")
  ("bin" "application/octet-stream")
  ("exe" "application/octet-stream")
  ("dump" "application/octet-stream")
  ("o" "application/octet-stream")
  ("so" "application/octet-stream")
  ("class" "application/java")
  ("eps" "application/postscript")
  ("ps" "application/postscript")
  ("dvi" "application/x-dvi")
  ("latex" "application/x-latex")
  ("rtf" "application/rtf")
  ("hqx" "application/mac-binhex40")
  ("sit" "application/x-stuffit")
  ("tex" "application/x-tex")
  ("texi" "application/x-texinfo")
  ("texinfo" "application/x-texinfo")
  ("doc" "application/msword")
  ("ppt" "application/powerpoint")
  ("mime" "message/rfc822")
  ("iso" "application/x-iso9660-image")
))
